baseurl = "https://www.eventslooped.com"
languageCode = "en"
title = "EventsLooped"
theme = "kiss"
copyright = "&copy; Ilya Nemtsev 2025"
disqusShortname = "ilikedos"
# Number of posts per page
pagination.pagerSize = 10
enableRobotsTXT = true
imgPad = 14
pygmentsUseClasses = true

[params.assets]
customCSS = ["css/custom.css"]

[params.rss]
includeContent = true # Includes whole content in rss
authorName = "Ilya Nemtsev" # Site author's full name
authorEmail = "eventslooped@gmail.com"

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "Eventslooped" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = ""
github = "inemtsev"
email = "eventslooped@gmail.com"
linkedin = "ilyanemtsev"
# instagram = ""

[params.social.config]
platforms = ["twitter","github","email","linkedin"]

[params.sections_left]
"/index.html" = "Blog"
# "##" = "Photos"
"/about-me" = "About me"

[taxonomies]
tag ="tags"

publishDir = "docs"

[markup.goldmark.renderer]
unsafe= true

[services.googleAnalytics]
ID = "G-5ZMD7C285E"
